### ISSUE TITLE
uvc1 was not found in /uvc-master/bin/

### ISSUE THREAD

**Issue by cmguodong** [genetronhealth/uvc#6]
as describe above, uvc1 was not found in /uvc-master/bin/

**Comment by zhaoxiaofei** [comment]
Did you run the command:  **./install-dependencies.sh && make clean && make all -j4 && make deploy** ?
If the above command is run successfully, then the binary executable uvc1 should be in the bin/ directory.

**Comment by cmguodong** [comment]
Hi Zhao,
thanks for your reply

Errors occurred after make clean / make all, details as follows:
----
g++  -o bcf_formats_generator1.out -std=c++14 -static-libstdc++ -Wall  bcf_formats_generator1.cpp
gcc   -O3 -o debarcode -DCOMMIT_VERSION="\"42537a6\"" -DCOMMIT_DIFF_SH="\"\"" -DCOMMIT_DIFF_FULL="\"\"" debarcode_main.c ext/htslib-1.11-lowdep/libhts.a -I ext/htslib-1.11-lowdep/ -pthread -lm -lz -lbz2 -llzma 
./bcf_formats_generator1.out > bcf_formats.step1.hpp
g++  -O3 -DNDEBUG -o uvc.rel.out  -std=c++14 -static-libstdc++ -Wall  -DCOMMIT_VERSION="\"42537a6\"" -DCOMMIT_DIFF_SH="\"\"" -DCOMMIT_DIFF_FULL="\"\"" CmdLineArgs.cpp common.cpp grouping.cpp logging.cpp main.cpp                     version.cpp  ext/htslib-1.11-lowdep/libhts.a -I ext/htslib-1.11-lowdep/ -pthread -lm -lz -lbz2 -llzma  -fopenmp # -l htslib
g++  -O3 -DNDEBUG -o uvc.cppt.out -std=c++14 -static-libstdc++ -Wall  -DCOMMIT_VERSION="\"42537a6\"" -DCOMMIT_DIFF_SH="\"\"" -DCOMMIT_DIFF_FULL="\"\"" CmdLineArgs.cpp common.cpp grouping.cpp logging.cpp main.cpp                     version.cpp  ext/htslib-1.11-lowdep/libhts.a -I ext/htslib-1.11-lowdep/ -pthread -lm -lz -lbz2 -llzma  -DUSE_STDLIB_THREAD # -l htslib
g++  -O2 -g -p    -o uvc.mt.out   -std=c++14 -static-libstdc++ -Wall  -DCOMMIT_VERSION="\"42537a6\"" -DCOMMIT_DIFF_SH="\"\"" -DCOMMIT_DIFF_FULL="\"\"" CmdLineArgs.cpp common.cpp grouping.cpp logging.cpp main.cpp                     version.cpp  ext/htslib-1.11-lowdep/libhts.a -I ext/htslib-1.11-lowdep/ -pthread -lm -lz -lbz2 -llzma  -fopenmp -fsanitize=address 
g++  -O2 -g -p    -o uvc.st.out   -std=c++14 -static-libstdc++ -Wall  -DCOMMIT_VERSION="\"42537a6\"" -DCOMMIT_DIFF_SH="\"\"" -DCOMMIT_DIFF_FULL="\"\"" CmdLineArgs.cpp common.cpp grouping.cpp logging.cpp main.cpp                     version.cpp  ext/htslib-1.11-lowdep/libhts.a -I ext/htslib-1.11-lowdep/ -pthread -lm -lz -lbz2 -llzma  -fsanitize=address
CmdLineArgs.cpp: 在成员函数‘int CommandLineArgs::initFromArgCV(int&, int, const char* const*)’中:
CmdLineArgs.cpp:126:1: 附注：变量跟踪大小越限，请不带 -fvar-tracking-assignments 重试
 CommandLineArgs::initFromArgCV(int & parsing_result_flag, int argc, const char *const* argv) {
 ^
CmdLineArgs.cpp: 在成员函数‘int CommandLineArgs::initFromArgCV(int&, int, const char* const*)’中:
CmdLineArgs.cpp:126:1: 附注：变量跟踪大小越限，请不带 -fvar-tracking-assignments 重试
 CommandLineArgs::initFromArgCV(int & parsing_result_flag, int argc, const char *const* argv) {
 ^
In file included from CmdLineArgs.hpp:4:0,
                 from main.hpp:6,
                 from main.cpp:2:
main_conversion.hpp:237:1:   in constexpr expansion of ‘calc_binom_10log10_likeratio<false, false>(1.0000000000000001e-1, 1.0e+1, 9.0e+1)’
main_conversion.hpp:237:77: 编译器内部错误：段错误
 STATIC_ASSERT_WITH_DEFAULT_MSG(abs(calc_binom_10log10_likeratio(0.1, 10, 90)) < 1e-4);
                                                                             ^
common.hpp:30:58: 附注：in definition of macro ‘STATIC_ASSERT_WITH_DEFAULT_MSG’
 #define STATIC_ASSERT_WITH_DEFAULT_MSG(x) static_assert((x), "Static assertion failed at " __FILE__ ":" STRINGIZE(__LINE__));
                                                          ^
0xacbb6f crash_signal
	../../gcc/toplev.c:383
0x8c0e5c bool vec_safe_reserve<tree_node*, va_gc>(vec<tree_node*, va_gc, vl_embed>*&, unsigned int, bool)
	../../gcc/vec.h:575
0x8c0e5c tree_node** vec_safe_push<tree_node*, va_gc>(vec<tree_node*, va_gc, vl_embed>*&, tree_node* const&)
	../../gcc/vec.h:669
0x8c0e5c add_local_decl(function*, tree_node*)
	../../gcc/function.c:6702
0xb1f220 remap_decls
	../../gcc/tree-inline.c:653
0xb1f2e6 remap_block
	../../gcc/tree-inline.c:721
0xb21248 copy_bind_expr
	../../gcc/tree-inline.c:794
0xb21248 copy_tree_body_r(tree_node**, int*, void*)
	../../gcc/tree-inline.c:1128
0xcaecd4 walk_tree_1(tree_node**, tree_node* (*)(tree_node**, int*, void*), void*, hash_set<tree_node*, default_hashset_traits>*, tree_node* (*)(tree_node**, int*, tree_node* (*)(tree_node**, int*, void*), void*, hash_set<tree_node*, default_hashset_traits>*))
	../../gcc/tree.c:11093
0xb1e492 copy_tree_body
	../../gcc/tree-inline.c:2965
0xb1e492 copy_fn(tree_node*, tree_node*&, tree_node*&)
	../../gcc/tree-inline.c:5987
0x72f342 cxx_eval_call_expression
	../../gcc/cp/constexpr.c:1387
0x72ace2 cxx_eval_constant_expression
	../../gcc/cp/constexpr.c:3127
0x72cc10 cxx_eval_outermost_constant_expr
	../../gcc/cp/constexpr.c:3653
0x6cec84 cp_convert_and_check(tree_node*, tree_node*, int)
	../../gcc/cp/cvt.c:651
0x6174ec convert_like_real
	../../gcc/cp/call.c:6590
0x61d2a8 build_over_call
	../../gcc/cp/call.c:7315
0x61f7e1 build_new_function_call(tree_node*, vec<tree_node*, va_gc, vl_embed>**, bool, int)
	../../gcc/cp/call.c:4114
0x6e6ee2 finish_call_expr(tree_node*, vec<tree_node*, va_gc, vl_embed>**, bool, bool, int)
	../../gcc/cp/semantics.c:2409
In file included from CmdLineArgs.hpp:4:0,
                 from main.hpp:6,
                 from main.cpp:2:
main_conversion.hpp:237:1:   in constexpr expansion of ‘calc_binom_10log10_likeratio<false, false>(1.0000000000000001e-1, 1.0e+1, 9.0e+1)’
main_conversion.hpp:237:77: 编译器内部错误：段错误
 STATIC_ASSERT_WITH_DEFAULT_MSG(abs(calc_binom_10log10_likeratio(0.1, 10, 90)) < 1e-4);
                                                                             ^
common.hpp:30:58: 附注：in definition of macro ‘STATIC_ASSERT_WITH_DEFAULT_MSG’
 #define STATIC_ASSERT_WITH_DEFAULT_MSG(x) static_assert((x), "Static assertion failed at " __FILE__ ":" STRINGIZE(__LINE__));
                                                          ^
0x69b641 cp_parser_postfix_expression
	../../gcc/cp/parser.c:6375
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.
**make: *** [uvc.st.out] 错误 1**
make: *** 正在等待未完成的任务....
0xacbb6f crash_signal
	../../gcc/toplev.c:383
0x8c0e5c bool vec_safe_reserve<tree_node*, va_gc>(vec<tree_node*, va_gc, vl_embed>*&, unsigned int, bool)
	../../gcc/vec.h:575
0x8c0e5c tree_node** vec_safe_push<tree_node*, va_gc>(vec<tree_node*, va_gc, vl_embed>*&, tree_node* const&)
	../../gcc/vec.h:669
0x8c0e5c add_local_decl(function*, tree_node*)
	../../gcc/function.c:6702
0xb1f220 remap_decls
	../../gcc/tree-inline.c:653
0xb1f2e6 remap_block
	../../gcc/tree-inline.c:721
0xb21248 copy_bind_expr
	../../gcc/tree-inline.c:794
0xb21248 copy_tree_body_r(tree_node**, int*, void*)
	../../gcc/tree-inline.c:1128
0xcaecd4 walk_tree_1(tree_node**, tree_node* (*)(tree_node**, int*, void*), void*, hash_set<tree_node*, default_hashset_traits>*, tree_node* (*)(tree_node**, int*, tree_node* (*)(tree_node**, int*, void*), void*, hash_set<tree_node*, default_hashset_traits>*))
	../../gcc/tree.c:11093
0xb1e492 copy_tree_body
	../../gcc/tree-inline.c:2965
0xb1e492 copy_fn(tree_node*, tree_node*&, tree_node*&)
	../../gcc/tree-inline.c:5987
0x72f342 cxx_eval_call_expression
	../../gcc/cp/constexpr.c:1387
0x72ace2 cxx_eval_constant_expression
	../../gcc/cp/constexpr.c:3127
0x72cc10 cxx_eval_outermost_constant_expr
	../../gcc/cp/constexpr.c:3653
0x6cec84 cp_convert_and_check(tree_node*, tree_node*, int)
	../../gcc/cp/cvt.c:651
0x6174ec convert_like_real
	../../gcc/cp/call.c:6590
0x61d2a8 build_over_call
	../../gcc/cp/call.c:7315
0x61f7e1 build_new_function_call(tree_node*, vec<tree_node*, va_gc, vl_embed>**, bool, int)
	../../gcc/cp/call.c:4114
0x6e6ee2 finish_call_expr(tree_node*, vec<tree_node*, va_gc, vl_embed>**, bool, bool, int)
	../../gcc/cp/semantics.c:2409
0x69b641 cp_parser_postfix_expression
	../../gcc/cp/parser.c:6375
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.
**make: *** [uvc.mt.out] 错误 1**
-----
I don't know what went wrong

**Comment by genetronhealth** [comment]
1. Does this error go away if you change
#define STATIC_ASSERT_WITH_DEFAULT_MSG(x) static_assert((x), "Static assertion failed at " __FILE__ ":" STRINGIZE(__LINE__));
into
#define STATIC_ASSERT_WITH_DEFAULT_MSG(x) ;
at https://github.com/genetronhealth/uvc/blob/441a6945fb3614b0d4a4dec1f4691af58301a817/common.hpp#L30 ?
2. what is the version of the g++ compiler that you are using?  ( you can get it with the command: g++ --version )

**Comment by cmguodong** [comment]
Thanks for your quick reply
1. as your suggestion， this error has gone away, UVC has been installed successfully  ^_^
2. the version of g++ is (GCC) 5.2.0

**Comment by genetronhealth** [comment]
You are welcome ^_^
It seems that static_assert in "g++ is (GCC) 5.2.0" is not fully supported.  
I tested with g++ (GCC) 6.3.0 and some higher versions of g++, and I did not encounter this error.

**Comment by genetronhealth** [comment]
Hi @cmguodong 

Is your issue fully resolved?
I also the installation part of the README.md at 
https://github.com/genetronhealth/uvc/commit/2a8ffb9187099077e27e34d621d41f9c9dab9d3f
to recommend g++ version of at least 6.3.0

If your issue is resolved, then I will close this issue.
